bazelbuild/bazel-bench

- benchmark.py
- utils/bazel.py
- utils/output_handling.py
Changes:
- Add a new "started_at" column to the csv output
- [Non-code] Created the column on BigQuery
Note: according to [`google-cloud-python`](https://github.com/googleapis/google-cloud-python/blob/11e310ab9f63f06252ff2b9ada201fd8c11ce06c/bigquery/google/cloud/bigquery/dbapi/types.py#L28), Python `datetime.datetime` type is mapped to `TIMESTAMP` type on BigQuery.
I've also created the column on BigQuery and verified that uploading works.
> Add a new "started_at" column to BigQuery table

- benchmark.py
- benchmark_test.py
We've been (sort of) breaking abstraction by performing `bazel.command` directly in the `_run_benchmark` method. This change would improve the overall code readability.
Changes:
- Use `_single_run` to perform the prefetch run
- Change the signature of _single_run to accept `args` instead of separating `expressions` and `options`.
- Minor: Change "build env" to "build event" in a log entry.
> Use _single_run to perform the prefetch run

- benchmark.py
- benchmark_test.py
- requirements.txt
**Why?**
We've been calling "raw" `git` commands with `subprocess`. This has a few disadvantages:
- ~Requires the internal navigation to various directories with `os.chdir`. This is prone to obscure bugs  e.g. if one forgets to change back to the correct directory.~
- Extracting the latest commit of a repository is troublesome.
We have been using the string "latest" to represent this. It's fine in the context of running the script in the command line and immediately consume the result, but on BigQuery it's wrong since "latest" at different points in time mean different commits.
GitPython addresses these issues.
**Changes:**
- Use GitPython to perform git interactions now.
- Replacing "latest" by getting the actual latest commit's SHA.
> Replace raw git bash commands with Gitpython

- benchmark.py
Changes:
- Default paths are now structured based on the platform.
Notes:
Results of calling `tempfile.gettempdir()`:
- On Windows: `'C:\\Users\\leba\\AppData\\Local\\Temp\\2'`
- On Linux & Mac: `'/tmp'`
> Convert default paths to appropriate format on Windows

- benchmark.py
Fix the default tmp path for output csv. Previously the path would look something like `/tmp/tmp/.bazel-bench/out` on Linux.
The fixed default tmp path is `/tmp/.bazel-bench/out`
None
None
> Fix default outpath

- benchmark.py
- benchmark_test.py
For git commits, we can't work out the topological order from the commit ID. Getting the order is important for displaying the data on a graph. To determine this order, we'll fetch the commit history from the repository and order the input commit (topological order) based on that.
- Sort input commits by topological order.
None
No
> Topological commit ordering

- benchmark.py
- utils/output_handling.py
This PR removes the unnecessary `sorted` function application to the collected data. It makes no sense to sort git commit hashes.
* Remove sorting of commit hashes when printing result to the cmdline and in the CSV output.
None
No
> Rm sorting of commit hashes in output

- benchmark.py
- requirements.txt
There's a vulnerability in the current version of urllib3.
https://github.com/bazelbuild/bazel-bench/network/alert/requirements.txt/urllib3/open
Change urllib3 version from 1.24.1 -> 1.24.2
None
No
> Fix Vulnerability With Dependency

- benchmark.py
- benchmark_test.py
- testutils/fakes.py
This PR adds the ability to execute commands in a specific working directory.
Add the `cwd` parameter in `_exec_command`.
None
No
> Add cwd to _exec_command

- utils/bazel_test.py
Fixes a failing test in bazel_test.py
> Fix failing Bazel test

- benchmark.py
We did not change the working directory to the `project_path` in the case of `--prefetch_ext_deps=False`, causing the tool to crash.
> Fix bug with --prefetch_ext_deps

- README.md
- benchmark.py
- utils/output_handling.py
The `data_directory` requirement to include the trailing slash made the code hard to read if we need to have a subdirectory structure under it. For example:
```
subdir = '%ssubdir' % (FLAGS.data_directory)
```
> Change data_directory requirement

- README.md
- benchmark.py
- benchmark_test.py
- utils/output_handling.py
This PR adds a new flag `--collect_json_profile` that allows us to collect JSON profiles from the runs, by performing them with [JSON profile flags](https://docs.bazel.build/versions/master/skylark/performance.html#json-profile). 
- Added a new flag & functionality
- Introduced a `bazel_bench_uid`, determined by the start time of the script, to act as a namespace for output files.
Closes: #18 
None.
No.
> Allow option to export JSON profile from runs

- benchmark.py
- utils/output_handling.py
This PR adds a new "platform" column to the CSV output. We need it to categorize the data collected with runs on BazelCI by platforms.
Yes.
> Add `platform` column to CSV & BQ output

- benchmark.py
- benchmark_test.py
- utils/output_handling.py
We need to specify the project id in BQ's client to connect to the correct project.
Otherwise, this value is interpreted from GOOGLE_APPLICATION_CREDENTIALS, which is not always what we want.
> Add project_id requirement to upload_data_to

- benchmark.py
- benchmark_test.py
This PR gets rid of all trailing slashes in the default dirs ti be consistent with an earlier change.
It also sets the paths for built Bazel binaries from `/tmp/.bazel-bench/bazel-bin/<commit>` to `/tmp/.bazel-bench/bazel-bin/<commit>/bazel`.
> Get rid of all trailing slashes in default dirs and change binary dir

- benchmark.py
- benchmark_test.py
This PR removes the sanity check for GOOGLE_APPLICATION_CREDENTIALS in the environment since our BazelCI Ubuntu VMs doesn't have that value set.
No.
> Remove GCP Credentials check

- BUILD
- WORKSPACE
- third_party/requirements.txt
- utils/BUILD
Fixes #29. Specify python version to run with the test targets.
Verified locally with Bazel 0.27 and with ` --incompatible_use_python_toolchains` enabled.
> Fix incompatibilities with --incompatible_use_python_toolchains

- README.md
- benchmark.py
- utils/BUILD
- utils/json_profiles_merger.py
- utils/json_profiles_merger_lib.py
- utils/json_profiles_merger_lib_test.py
- utils/output_handling.py
This PR adds a tool to merge JSON profiles that we collect and present an aggregation (median) of the event durations.
Next step: Incorporate this into bazel-bench-nightly as the final step.
- Add json_profile_merger tool.
- Change upload_csv signature to detach flag parsing logic.
- Update README.
Yes. Create a new table `json_profiles_aggr`.
> Add json-profile-merger tool

- BUILD
- README.md
- benchmark.py
- benchmark_test.py
- third_party/requirements.txt
- utils/BUILD
- utils/bigquery_upload.py
- utils/output_handling.py
- utils/storage_upload.py
This PR allows uploading CSV output to GCP Storage. This is part of the pipeline that generates daily reports for Bazel performance.
Nest step: upload collected JSON profiles to Storage.
- Refactored `output_handling` to 3 separate modules: `output_handling`, `bigquery_upload` and `storage_upload`. (This is a workaround for https://github.com/bazelbuild/rules_python/issues/14. Refactoring to separate modules & targets to prevent the `google` namespaces from clashing).
- Added a function to upload files to Storage.
- Added new flags: `--upload_to_storage` and `--csv_file_name`
- Renamed old flag: `--upload_data_to` -> `--upload_to_bigquery`
None
**Does this require a …
> Upload CSV output to Storage

- utils/BUILD
- utils/json_profiles_merger.py
- utils/json_profiles_merger_lib.py
- utils/json_profiles_merger_lib_test.py
For our current purposes in the daily report, it suffices to only output the median duration of each build phase, instead of listing every single event. This PR adds a flag that allows us to do that.
- Add `--only_phases` to `json_profiles-merger`
- Switch the binary target to using python 2.
None
None
> [JSON profile] Add an option to only aggregate phase markers

- utils/BUILD
We need to use python 2 for these targets too, else they'll crash on bazel-bench-nightly.
> Use python 2 for uploaders targets

- utils/output_handling.py
Remove the baked-in `.csv` suffix to file name in `output_handling.export_csv`.
> Remove baked-in .csv extension in output_handling

- benchmark.py
- utils/bazel.py
- utils/bazel_test.py
- utils/logger.py
- utils/values.py
This PR fixes #39 by adding an error log entry when the exit code of a bazel command returns a non-zero code. The actual _exclusion_ of the failed runs from the final dashboard/report will be done somewhere else (in the report generator itself).
Also fixes #33.
Update: The new summary table + exit-code message:
Issue #39.
> Handle the case when exit status != 0

- benchmark.py
- utils/values.py
This PR excludes failed runs from the summary table and also clearly state which run failed with which exit code.
Screenshot:
Fixes #49.
> Exclude failed runs from summary table

- README.md
- benchmark.py
- benchmark_test.py
Bazel-bench runs would sometime fail on Linux environments due to a race condition. This is tracked at https://github.com/bazelbuild/bazel/issues/3236.
As a workaround, we need to apply `--sandbox_tmpfs_path=/tmp` to our runs on Linux. This PR injects that flag to the list of args if `os.platform.startswith('linux')`.
This PR also moves the root of bazel-bench's output directory to `~/.bazel-bench/` instead of `/tmp/.bazel-bench/`, so that the flag `sandbox_tmpfs_path` (whose value is hardcoded to `/tmp/`) works.
Fixes #42.
> Change bazel-bench root dir & add --sandbox_tmpfs_path=/tmp

- report/generate_report.py
This PR:
- Adapts the URLs to the new domain-named bucket.
- Excludes failed runs from the final graphs.
- Adds a link to the project's GitHub repository.
Sample output: https://perf.bazel.build/bazel/2019/07/02/report.html
> Misc bugs in the report

- report/generate_report.py
This PR adds the following components to the charts:
- A bar that displays the range of data (min & max values) for each set of measurement.
- A tooltip that shows the values of every build phase.
Result: https://perf.bazel.build/bazel/2019/06/21/report.html
(Please ignore the missing data)
> Added better tooltip & [Min, Max] bar

- benchmark.py
Use OrderedDict instead of dict to preserve the commit order when generating data.
> Fixed bug with random commit order

- benchmark.py
This PR adds a new option that specifies the directory to store the built bazel binaries.
This is a step towards #59.
> Add an option to specify binary directory

- README.md
- benchmark.py
- benchmark_test.py
This PR adds a new flag `--bazel_binaries` to allow benchmarking of pre-built bazel binaries.
Other changes:
* The script now fails if one of the specified bazel commits doesn't exist in the `master` branch of the specified repo.
* Added a more prominent message in the log to stdout
> --bazel_binaries flag

- utils/json_profiles_merger_lib.py
- utils/json_profiles_merger_lib_test.py
This adds additional information to the `json_profile_merger` tool to enable further analysis of action durations.
Adds new columns including `min`, `max`, and `count` whilst 'dur' is renamed to 'median'
This will require changes towards the BigQuery table structure.
> Add min/max/count to json profiles merger

- report/generate_report.py
Whether we want to upload the report or not, we still need the storage bucket details, therefore it's wrong to use it as a signal to decide if we upload the report.
- New flag: `--upload_report`
None.
The pipeline step now has to explicitly include `--upload_report=True`.
cc @meisterT
> Use a new flag to decide whether to upload the report

- benchmark.py
- benchmark_test.py
This PR adds the logic to handle the case when an input commit digest is short (e.g. the typical 7-char digest).
> Unify SHA digests length

- report/generate_report.py
The old query was wrong (LIMIT 10) and fragile (it was relying on the bazel_commit=project_commit property to determine the last commit of the day). This PR fixes that.
Verified that the new query works.
I'll re-generate the report once this is merged.
Example: https://perf.bazel.build/bazel/2020/02/05/report_fixed.html
> Fix query for historical data in daily report

- benchmark.py
- utils/output_handling.py
This PR adds a new column `project_label` to the CSV output. We used to use `project_source` to be the identification of each project, but sometimes we want to benchmark different aspects of a project e.g. `tf-python` or `tf-cpp`, so a `project_label` field is necessary.
Yes.
> Added project_label column

- utils/output_handling.py
This caused a breakage in Bazel-bench, since BigQuery doesn't match CSV column based on column name (matches the data by column order instead).
No.
> Moved new column to the back

- benchmark.py
- benchmark_test.py
Not all binaries work on all platforms, so when a platform is specified, we should use it to classify built binaries. This is especially relevant for our pipeline on BuildKite.
> Separate built binaries by platforms.

- utils/json_profiles_merger.py
- utils/json_profiles_merger_lib.py
It might save someone some time looking at the stack trace.
jsonprofilemerger did not provide any check for an empty parameter list, but errored further into execution when none were provided.
The new output is still not as clean as I'd like, but I wasn't sure the best way to handle reporting this to the user.
Example new output:
```
Traceback (most recent call last):
File "/home/user/.cache/bazel/_bazel_user/c0fe45a85c85ea43d6d62cbc57b2f48c/execroot/__main__/bazel-out/k8-py2-fastbuild/bin/utils/json_profiles_merger.runfiles/__main__/utils/json_profiles_merger.py", line 70, in <module>
app.run(main)
File "/home/user/.cache/bazel/_bazel_user/c0fe45a85c85ea43d6d62cbc57b2f48c …
```
> Add error for no parameters on jsonprofilemerger

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
To fix `//:benchmark_test` in https://buildkite.com/bazel/bazel-bench/builds/474
Installed missing pip package
No
No
> Ensure gitdb is installed

- utils/json_profiles_merger.py
This PR introduces a flag for json_profile_merger which allows the specification of a folder for loading json profiles from. This is necessary when the list of json profiles to process is exceedingly large.
Loading several thousand json profiles via command line arguments can be slightly tricky. Specifying a folder for this can be much easier.
N/A
No.
> Add input_profile_dir flag to json_profile_merger

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
- third_party/requirements.txt
- utils/values_test.py
To fix the failing CI builds on Mac (Fixes https://github.com/bazelbuild/bazel/issues/12076)
Also dropping the `ubuntu1604` environment, as we no longer do benchmarks on it (Fixes #99 )
> Bump numpy and scipy versions

- report/generate_master_report.py
Adds a link back to this project from the master report to have an easy way to reach docs.
> Add subtle link back to bazel bench project.

- benchmark.py
Already exposes some info while the script is still running.
Example:
```
I1126 16:58:52.522313 140285878904640 logger.py:34] Preparing /home/twerth/bazel clone.
I1126 16:58:52.522784 140285878904640 logger.py:34] Path /home/twerth/.bazel-bench/project-clones/d8eb7a85967b22409442664d380222c0 exists. Updating...
I1126 16:58:52.687012 140285878904640 logger.py:34] === BENCHMARKING BAZEL: /usr/bin/bazel-real, PROJECT: 5a91c25ca43547870bcf73cf4b427277c7f62d8d ===
I1126 16:58:52.687237 140285878904640 logger.py:34] Pre-fetching external dependencies...
I1126 16:58:52.687336 140285878904640 logger.py:34] Executing Bazel command: bazel  build --sandbox_tmpfs_path=/tmp --nostamp --noshow_progress --color=no
Starting local Bazel server and connecting to it...
I1126 16:58:55.809604 140285878904640 …
```
> Add log message about individual runs.

- benchmark.py
- utils/benchmark_config.py
The nightly benchmark crashed here. This PR fixes the crash by providing the json aggregator with info from the benchmark config object.
> Fix JSON aggregator crashing with benchmark config

- benchmark.py
project_source was missing in the summary. This PR fixes that.
Before:
```
RESULTS:
Bazel commit: 520c0f912e510f69e4457ea935f18a1b35df3932, Project commit: b1c40e1de81913a3c40e5948f78719c28152486d, Project source: None
metric          mean                median          stddev      pval   
wall:    1.115s               1.115s              0.000s             
cpu:    8.830s               8.830s              0.000s             
system:    0.700s               0.700s              0.000s             
memory:   27.000MB             27.000MB             0.000MB            
Bazel commit: 20f62f87c40c5f83eb65b4417cf28f1d800013b0, Project commit: b1c40e1de81913a3c40e5948f78719c28152486d, Project source: None
metric          mean                median …
```
> Fix missing project source in summary text.

- README.md
- benchmark.py
- benchmark_test.py
- utils/bazel.py
- utils/bazel_test.py
- utils/benchmark_config.py
- utils/benchmark_config_test.py
This makes the script interface a bit simpler (1 fewer flag), and reduces the risk of users forgetting to turn on this flag. The memory collection is done _after_ each build so it doesn't affect the other numbers.
TODO:
> Make memory collection the default and only behavior

- README.md
- benchmark.py
- utils/benchmark_config.py
- utils/benchmark_config_test.py
Less than 5 runs rarely show meaningful results.
> Bump default number of runs from 3 to 5.

- third_party/requirements.txt
https://github.com/bazelbuild/bazel-bench/commit/0ad9b557594716517672e5b51c03bf8928ab2829 broke our nightly benchmarks. This commit attempts to fix it.
> Replace this line with your answer.
> Replace this line with your answer.
> Replace this line with your answer.
> Replace this line with your answer.
> Bump google-resumable-media.

- third_party/requirements.txt
Add a explicit dependency on cpython to make it work on glinux machines.
> Make dependency on cython explicit.

- benchmark.py
- benchmark_test.py
The script previously used the tuple `(bazel_identifier, project_commit)` to identify a data point. This is not enough to differentiate benchmark units, in case we want to benchmark the same bazel commit/binary but with different command lines. This PR fixes that by adding the unit number to this identifying tuple.
Also removed obsolete param `bep_json_dir` in `_run_benchmark`.
Test run:
Fixes #113.
> Support benchmark units with the same bazel_commit/bazel_binary

- benchmark.py
This PR adds an additional flag --project_branch for configuring which branch of a given git project to benchmark from.
Sorry. I deleted my previous fork so I can't just reopen the previous PR.  Sending it again here.
> Add flag for configuring the branch of the project to pull from

- benchmark.py
- benchmark_test.py
It doesn't necessarily match the branch to be checked out for the target
project, which is given by the --project_branch flag.
> Always check out the Bazel `master` branch.

- WORKSPACE
With the current version, bazel-bench fails to run successfully on MacOS for
reasons I don't fully understand (something to do with locating the pip deps
inside the virtual environment). Instead of trying to understand them, I'm
upgrading to the latest rules_python release, which works fine.
> Upgrade rules_python.

- .bazelci/postsubmit.yml
- .bazelci/presubmit.yml
- WORKSPACE
- third_party/requirements.txt
The currently specified versions of scipy and numpy no longer work with
Python 3.10, but their latest versions are not available for Python 3.6,
which is the version available on the Ubuntu 18.04 CI machines.
Using a hermetic interpreter ensures builds are reproducible irrespective
of the interpreter version available on the host machine.
Also note that it's not necessary to run pip on the CI machines. The
Python rules are already able to fetch the dependencies.
> Use hermetic Python.

- benchmark.py
Also use subprocess.run() which has a simpler interface than Popen().
> Fail the script if an external command returns a nonzero exit status.

- benchmark.py
The argument is called collect_profile, not collect_json_profiles.
> Fix keyword argument in call to BenchmarkConfig.from_flags.

- benchmark.py
This ensures that a preexisting clone for one remote (say, bazelbuild/bazel) will not be reused when building Bazel from another remote (say, tjgq/bazel) which causes confusing results when the desired branch or commit doesn't exist in the former.
> Clone Bazel to a per-remote directory, like we do for projects.

- benchmark.py
- utils/benchmark_config.py
- utils/benchmark_config_test.py
The `'env_configure' in unit` presence check introduced in 5ce2dea doesn't work, as the command line flag defaults to None but the field might be missing entirely from the configuration file. Instead, normalize its presence and check against None. This mirrors how we handle other configuration fields.
> Fix crash when env_configure is not explicitly given in the command line.

- WORKSPACE
This is needed in order to flip the disallow empty globs flag.
Version 0.11.0 makes it possible.
0.13.0 is the latest available at the time of this bump.
The idea is to fix the issues of Bazel Bench tests when being run with incompatible_disallow_empty_glob
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1301#0183e377-9bfb-43fe-b329-fd314fb22b06
None
I don't think so but I don't know
> Bump rules_python to 0.11.0

- utils/benchmark_config.py
- utils/benchmark_config_test.py
Support the bazel command's usage of `--` to separate the targets from the options.
Example:
```
bazel build --foo -- //target_bar -//exclude/...
```
> Support -- syntax

- benchmark.py
- benchmark_test.py
Removed couple of flags:
* experimental_profile_cpu_usage
* experimental_json_trace_compression
`experimental_profile_cpu_usage` is removed starting from Bazel 5.0 (and is always set to `true`). More [here](https://blog.bazel.build/2022/01/19/bazel-5.0.html#general).
`experimental_json_trace_compression` doesn't seem to exist anymore. Also according to [this](https://github.com/bazelbuild/bazel/issues/10171#issuecomment-550974706) comment is implicitly set to `true`.
> [Profile] Remove obsolete (non-existent) flags

- benchmark.py
- benchmark_test.py
Make `clean` and `shutdown` commands toggle-able. Right now, the benchmarking script cleans and shuts down the bazel process after each run. This is not always needed (especially when performing incremental benchmarks). 
* *New changes / Issues that this PR fixes:**
It doesn't entirely fix issue #[153](https://github.com/bazelbuild/bazel-bench/issues/153), but it addresses part of it.
> [Clean, Shutdown] Add flags to skip clean & shutdown

- benchmark.py
- utils/benchmark_config.py
- utils/benchmark_config_test.py
Extension to https://github.com/bazelbuild/bazel-bench/pull/164. This allows to specify `clean` and `shutdown` flags in the config (yaml) file.
> Extend the `clean` and `shutdown` flags to BenchmarkConfig.py

- .bazelrc
We should properly opt in to bzlmod to fix https://github.com/bazelbuild/bazel-bench/issues/168
> Disable bzlmod to make the tests green again.

- WORKSPACE
Necessary after the flip to --incompatible_struct_has_no_methods.
https://github.com/bazelbuild/bazel/commit/8f18d36
> Update rules_python to 0.27.1
