ISSUE_TEMPLATE.md
PULL_REQUEST_TEMPLATE.md
README.md
benchmark.py

This PR adds more details to the README file and 2 template files for Issue and Pull Request.
- Add ISSUE_TEMPLATE.md and PULL_REQUEST_TEMPLATE.md
- Fixed a typo in flag description.
None
No

Improve docs & introduce issue/pull request templates

---

benchmark.py
benchmark_test.py
utils/bazel_args_parser_test.py
utils/bazel_test.py
utils/output_handling.py
utils/values_test.py

Remove unnecessary imports from `__future__`.
Remove unnecessary imports from `__future__`.
None
No.

Rm unnecessary imports from __future__

---

.bazelci/presubmit.yml

This is to set up a BazelCI project for `bazel-bench`
Added `.bazelci/presubmit.yml`
None
No

Add bazelci config

---

.bazelci/presubmit.yml

Also build on Mac.

---

BUILD
README.md
benchmark.py
benchmark_test.py
testutils/BUILD
testutils/fakes.py
utils/BUILD
utils/bazel.py
utils/bazel_args_parser.py
utils/bazel_args_parser_test.py
utils/bazel_test.py
utils/logger.py
utils/output_handling.py

A quick fix of general code formatting.
No

Fix formatting

---

.bazelci/postsubmit.yml
.bazelci/presubmit.yml

Enable include_json_profile for CI.

Enable include_json_profile for CI

---

README.md

Add project_id in README after #26.

---

README.md
report/generate_report.py

This PR adds a generator for the daily performance report. An example of a generated report can be found [here](https://bazel-bench.storage.googleapis.com/bazel/2019/06/21/report.html).
This PR only concerns the generation/format of the report, not the data generation.
No.

Add Report Generator Script

---

report/generate_report.py

This PR allows the report to list the full list of commits, while highlighting which ones we benchmarked.
Example: https://perf.bazel.build/bazel/2019/07/11/report.html

Include full commit list in report & bold the benchmarked ones.

---

benchmark.py

We failed to check if the flag is None and that caused the nightly script to fail. This PR fixes it.

Fixed bug with bazel_binaries flag

---

report/generate_report.py

Next to consistency this has the nice side effect that Mac is on top and
it is the most stable platform.

Sort by platform.

---

report/generate_report.py

Collapse commit and file lists by default.

---

WORKSPACE
third_party/requirements.txt
utils/BUILD
utils/benchmark_config.py
utils/benchmark_config_test.py

This adds the config-file interface module. It will be linked up with the main script in a subsequent PR.
A step towards #70.

Add config file handling module

---

benchmark.py
utils/output_handling.py

The script now exports the summary to a txt file. We have plans to include this summary in the daily report.

Export the benchmark summary to a txt file

---

third_party/requirements.txt

Fixes https://github.com/bazelbuild/bazel/issues/12076.
Verified locally with my MBP.
Related: https://github.com/abseil/abseil-py/pull/126

Update absl to 0.9.0

---

BUILD
README.md
benchmark.py
benchmark_test.py
report/BUILD
report/generate_master_report.py
report/generate_report.py
utils/BUILD
utils/bazel.py
utils/bazel_args_parser.py
utils/bazel_args_parser_test.py
utils/bazel_test.py
utils/benchmark_config.py
utils/benchmark_config_test.py
utils/bigquery_upload.py
utils/json_profiles_merger.py
utils/json_profiles_merger_lib.py
utils/json_profiles_merger_lib_test.py
utils/logger.py
utils/output_handling.py
utils/storage_upload.py
utils/values.py

This is a no-op formatting change of the codebase.

Formatting changes.

---

README.md
utils/benchmark_config.py
utils/benchmark_config_test.py

This PR updates the specifications of benchmark-config to match the current intended behavior.

Update the specs of benchmark-config.

---

benchmark.py

Fixes #97 .
The table can be adjusted to look better, but not now.

Change memory unit to MB

---

README.md

Update the README with more explicit instructions, especially regarding virtual environment.

Update README with more explicit instructions (venv)

---

.bazelci/postsubmit.yml
.bazelci/presubmit.yml
third_party/requirements.txt

Fixes https://github.com/bazelbuild/continuous-integration/issues/1099.

Fix build with Xcode 12.4 and native Python 3

---

third_party/requirements.txt

Update another dependency.

---

third_party/requirements.txt

Fixing https://github.com/bazelbuild/continuous-integration/issues/1284

Upgrade scipy version
